set OUTPUTFILE=appLittleConstructorThreeJS.js
set JS_DIR=js
set OBJ_DIR=obj
set MOCKED_FILE=mockedObj.js

del %OUTPUTFILE%

type %JS_DIR%\license.js >> %OUTPUTFILE%  
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% jsGameEngine.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% jsGameEngine.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% space.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% vector2D.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% vector.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% triangle.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% mesh.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% piece.js
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% pieceFactory.js  
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% linkPoint.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% cursor.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% bluePlane.js 

call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% spaceThree.js 

REM Convert all .ojb files to .var files.
call java -jar file2var.jar -i %OBJ_DIR%\cursorMark.OBJ -o %OBJ_DIR%\cursorMark.VAR
call java -jar file2var.jar -i %OBJ_DIR%\groundMark.OBJ -o %OBJ_DIR%\groundMark.VAR
call java -jar file2var.jar -i %OBJ_DIR%\holeMark.OBJ -o %OBJ_DIR%\holeMark.VAR

call java -jar file2var.jar -i %OBJ_DIR%\RAILING.OBJ -o %OBJ_DIR%\RAILING.VAR
call java -jar file2var.jar -i %OBJ_DIR%\CABRIADA.OBJ -o %OBJ_DIR%\CABRIADA.VAR
call java -jar file2var.jar -i %OBJ_DIR%\PILAR_TALL.OBJ -o %OBJ_DIR%\PILAR_TALL.VAR
call java -jar file2var.jar -i %OBJ_DIR%\PILAR_MEDIUM.OBJ -o %OBJ_DIR%\PILAR_MEDIUM.VAR
call java -jar file2var.jar -i %OBJ_DIR%\PILAR_SMALL.OBJ -o %OBJ_DIR%\PILAR_SMALL.VAR
call java -jar file2var.jar -i %OBJ_DIR%\PILAR_SMALL.mtl -o %OBJ_DIR%\PILAR_SMALL_MTL.VAR
call java -jar file2var.jar -i %OBJ_DIR%\ROOF.OBJ -o %OBJ_DIR%\ROOF.VAR
call java -jar file2var.jar -i %OBJ_DIR%\BOARD.OBJ -o %OBJ_DIR%\BOARD.VAR
call java -jar file2var.jar -i %OBJ_DIR%\DOOR.OBJ -o %OBJ_DIR%\DOOR.VAR
call java -jar file2var.jar -i %OBJ_DIR%\WINDOW.OBJ -o %OBJ_DIR%\WINDOW.VAR
call java -jar file2var.jar -i %OBJ_DIR%\WINDOW.mtl -o %OBJ_DIR%\WINDOW_MTL.VAR
call java -jar file2var.jar -i %OBJ_DIR%\SOCLE.OBJ -o %OBJ_DIR%\SOCLE.VAR
call java -jar file2var.jar -i %OBJ_DIR%\FLOOR.OBJ -o %OBJ_DIR%\FLOOR.VAR
call java -jar file2var.jar -i %OBJ_DIR%\house.bpl -o %OBJ_DIR%\house.var

REM Delete mockedFile.js
del %JS_DIR%\%MOCKED_FILE%
echo. >> %JS_DIR%\%MOCKED_FILE%
echo // This file is autogenerated, if you add some byte it will be  >> %JS_DIR%\%MOCKED_FILE%
echo // deleted in the next iteration.  >> %JS_DIR%\%MOCKED_FILE%
echo.  >> %JS_DIR%\%MOCKED_FILE%
echo var mockedObj = new Map(); >> %JS_DIR%\%MOCKED_FILE%
echo var item = ""; >> %JS_DIR%\%MOCKED_FILE%
echo. >> %JS_DIR%\%MOCKED_FILE%

call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% cursorMark cursorMark.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% groundMark groundMark.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% holeMark holeMark.obj

call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% RAILING RAILING.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% CABRIADA CABRIADA.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% PILAR_TALL PILAR_TALL.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% PILAR_MEDIUM PILAR_MEDIUM.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% PILAR_SMALL PILAR_SMALL.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% ROOF ROOF.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% BOARD BOARD.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% DOOR DOOR.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% WINDOW WINDOW.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% FLOOR FLOOR.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% SOCLE SOCLE.obj
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% house HOUSE.bpl

call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% WINDOW_MTL WINDOW.mtl
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% WINDOW_JPG window.jpg

call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% PILAR_SMALL_MTL PILAR_SMALL.mtl
call addToMockedFile.bat %JS_DIR%\%MOCKED_FILE% %OBJ_DIR% PILAR_SMALL_JPG oak.jpg

call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% mockedObj.js 
call addFileWithHeader.bat %OUTPUTFILE% %JS_DIR% app.js 

copy C:\Users\mfontana\Downloads\*.bpl obj\
del C:\Users\mfontana\Downloads\*.bpl

copy C:\Users\mfontana\Downloads\*.ppl obj\
del C:\Users\mfontana\Downloads\*.ppl

cls

